# Generated by Django 5.2.16 on 2026-07-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, help_text='Nomor Induk Pegawai. Diisi hanya untuk dosen.', max_length=50, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nim',
            field=models.CharField(blank=True, help_text='Nomor Induk Mahasiswa. Diisi hanya untuk mahasiswa.', max_length=50, verbose_name='NIM'),
        ),
    ]
