# Generated by Django 5.2.16 on 2026-07-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('status', models.CharField(choices=[('berlangsung', 'Berlangsung'), ('selesai', 'Selesai'), ('pelanggaran', 'Dihentikan (Pelanggaran)')], default='berlangsung', max_length=20, verbose_name='Status Sesi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('total_nilai', models.IntegerField(blank=True, null=True, verbose_name='Total Nilai')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='Heartbeat Terakhir')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_ujian', to=settings.AUTH_USER_MODEL, verbose_name='Mahasiswa')),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi', to='exams.ujian', verbose_name='Ujian')),
            ],
            options={
                'verbose_name': 'Sesi Ujian',
                'verbose_name_plural': 'Daftar Sesi Ujian',
                'ordering': ['-waktu_mulai'],
                'unique_together': {('mahasiswa', 'ujian')},
            },
        ),
        migrations.CreateModel(
            name='Jawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.TextField(blank=True, verbose_name='Teks Jawaban')),
                ('nilai', models.IntegerField(blank=True, choices=[(0, '0 — Tidak Relevan'), (5, '5 — Sebagian Benar'), (10, '10 — Lengkap dan Tepat')], null=True, verbose_name='Nilai')),
                ('alasan_nilai', models.TextField(blank=True, verbose_name='Alasan Penilaian AI')),
                ('grading_status', models.CharField(choices=[('pending', 'Menunggu Penilaian'), ('processing', 'Sedang Dinilai'), ('done', 'Selesai Dinilai'), ('failed', 'Gagal Dinilai')], default='pending', max_length=20, verbose_name='Status Penilaian')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submit')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Dinilai')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='exams.soal', verbose_name='Soal')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='submissions.sesiujian', verbose_name='Sesi Ujian')),
            ],
            options={
                'verbose_name': 'Jawaban',
                'verbose_name_plural': 'Daftar Jawaban',
                'ordering': ['soal__nomor_urut'],
                'unique_together': {('sesi', 'soal')},
            },
        ),
    ]
