# Generated by Django 5.2.16 on 2026-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawaban',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Cosine similarity jawaban mahasiswa vs kunci jawaban (0.0 - 1.0). Dari model embedding.', null=True, verbose_name='Skor Kemiripan Semantik'),
        ),
    ]
