# Generated by Django 5.2.16 on 2026-07-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='submissions.sesiujian', verbose_name='Sesi Ujian')),
            ],
            options={
                'verbose_name': 'Log Heartbeat',
                'verbose_name_plural': 'Log Heartbeat',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='PelanggaranLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('tab_baru', 'Membuka Tab/Jendela Baru'), ('window_blur', 'Berpindah Aplikasi/Jendela'), ('fullscreen_exit', 'Keluar dari Mode Layar Penuh'), ('heartbeat_timeout', 'Koneksi Terputus (Heartbeat Timeout)')], max_length=30, verbose_name='Jenis Pelanggaran')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pelanggaran')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan Tambahan')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent Browser')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelanggaran', to='submissions.sesiujian', verbose_name='Sesi Ujian')),
            ],
            options={
                'verbose_name': 'Log Pelanggaran',
                'verbose_name_plural': 'Log Pelanggaran',
                'ordering': ['-timestamp'],
            },
        ),
    ]
