# Generated by Django 5.2.16 on 2026-07-17 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Mata Pelajaran')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Mata Pelajaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to=settings.AUTH_USER_MODEL, verbose_name='Dosen Pengampu')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Daftar Mata Pelajaran',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300, verbose_name='Judul Ujian')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi / Petunjuk Ujian')),
                ('durasi_menit', models.PositiveIntegerField(default=90, verbose_name='Durasi (menit)')),
                ('kelas_target', models.CharField(help_text='Pisahkan dengan koma jika lebih dari satu kelas. Contoh: TI-3A, TI-3B', max_length=200, verbose_name='Kelas yang Diizinkan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('aktif', 'Aktif'), ('selesai', 'Selesai')], default='draft', max_length=20, verbose_name='Status Ujian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_ujian', models.DateField(blank=True, null=True, verbose_name='Tanggal Ujian')),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujian', to='exams.matapelajaran', verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name': 'Ujian',
                'verbose_name_plural': 'Daftar Ujian',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_urut', models.PositiveIntegerField(verbose_name='Nomor Soal')),
                ('pertanyaan', models.TextField(verbose_name='Pertanyaan')),
                ('referensi_jawaban', models.TextField(help_text='Jawaban kunci/acuan yang digunakan AI sebagai panduan penilaian.', verbose_name='Referensi Jawaban')),
                ('kata_kunci', models.TextField(blank=True, help_text='Pisahkan dengan koma. Contoh: enkapsulasi, inheritance, polimorfisme', verbose_name='Kata Kunci Penting')),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='exams.ujian', verbose_name='Ujian')),
            ],
            options={
                'verbose_name': 'Soal',
                'verbose_name_plural': 'Daftar Soal',
                'ordering': ['ujian', 'nomor_urut'],
                'unique_together': {('ujian', 'nomor_urut')},
            },
        ),
    ]
