# Generated by Django 5.2.16 on 2026-07-17 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matapelajaran',
            options={'ordering': ['nama'], 'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Daftar Mata Kuliah'},
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah', to=settings.AUTH_USER_MODEL, verbose_name='Dosen Pengampu'),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='kode',
            field=models.CharField(max_length=20, unique=True, verbose_name='Kode Mata Kuliah'),
        ),
        migrations.AlterField(
            model_name='matapelajaran',
            name='nama',
            field=models.CharField(max_length=200, verbose_name='Nama Mata Kuliah'),
        ),
    ]
