# Generated by Django 5.2.16 on 2026-07-21 21:28

import apps.exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_rename_matapelajaran_relatedname_to_matakuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='tahun_ajaran',
            field=models.CharField(blank=True, default=apps.exams.models.get_tahun_ajaran_default, help_text='Format: YYYY/YYYY. Contoh: 2025/2026. Diisi otomatis dari tanggal sekarang.', max_length=20, verbose_name='Tahun Ajaran'),
        ),
    ]
