# Generated by Django 5.2.16 on 2026-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_add_tahun_ajaran_to_ujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='referensi_embedding',
            field=models.JSONField(blank=True, help_text='Vektor embedding dari referensi_jawaban. Di-generate otomatis oleh sistem.', null=True, verbose_name='Embedding Kunci Jawaban'),
        ),
    ]
